spring:
    datasource:
        url: jdbc:h2:mem:muslim2025    
        username: muslim2025
        password: 
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: create # valid, update, create-drop, none
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
server:
    port: 8080